language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    #- addon-google_apis-google-$ANDROID_API_LEVEL
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-m2repository
    #- extra-google-google_play_services
    #- extra-android-support
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL

  licenses:
    - '.+'

before_install:
  # - echo y | sudo apt-get update
  #- echo y | sudo apt-get install openjdk-7-jre
  #- export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  #- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  #- export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew

before_script:
  #- echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb shell svc power stayon true
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0

script:
  - ./gradlew jacocoDebugReport
  - ./gradlew build connectedCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
