language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - COMPILE_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    # Using Emulator for an older Android version, because there is no newer emulator, which works in travis-ci
    - EMULATOR_API_LEVEL=24
    - EMULATOR_ABI=armeabi-v7a
    - EMULATOR_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$COMPILE_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-$EMULATOR_ABI-google_apis-$EMULATOR_API_LEVEL

  licenses:
    - '.+'

before_install:
  # - echo y | sudo apt-get update
  #- echo y | sudo apt-get install openjdk-7-jre
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew

before_script:
  - uname -a
  - android list targets
  - ls -la $HOME/.android/**/*
  - ls -la $HOME/**/*
  # Create and start emulator
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $EMULATOR_ABI --tag $EMULATOR_TAG
  - ls -la $HOME/.android/**/*
  - ls -la $HOME/**/*
  - cat $HOME/.android/avd/test.avd/config.ini
  - cp res-src/avd_config.ini $HOME/.android/avd/test.avd/config.ini
  - cat $HOME/.android/avd/test.avd/config.ini
  - emulator -avd test -no-window &
  - travis_wait 30 android-wait-for-emulator
  # Previous command seems to end too early, so wait a bit more
  # On multilined commands: https://gitlab.com/gitlab-org/gitlab-ci/issues/258 and http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
  - |
    while ! adb shell getprop init.svc.bootanim; do
      echo Waiting for boot animation to end
      sleep 10
    done
  # Another method. Should print SDK version number to console
  # See http://stackoverflow.com/questions/28195080/unknown-api-level-error-when-trying-to-run-instrumentation-test
  - |
    while ! adb shell getprop ro.build.version.sdk; do
      echo Waiting for ro.build.version.sdk value from device
      sleep 10
    done
  - adb devices
  - adb shell input keyevent 82 &
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0

script:
  - ./gradlew jacocoDebugReport
  - ./gradlew build connectedCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
